---
title: "Module 7"
author: "Emily Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Challenge 1
```{r Challenge 1}
x <- c(1,2,3,4,5,6,7,8,9,10,100,1000)
gm1 <- function(x) {
    prod(x)^(1/length(x))
}
gm1(x)
# prod adds it together
# 1/length(x) divides by size of set

gm2 <- function(x) {
    exp(mean(log(x))) #nesting functions inside?
}
gm2(x)

x <- c(1,2,3,4,5,6,7,8,NA,10,100,1000)
x<- na.omit(x)
gm3 <- function(x) { 
    prod(x)^(1/length(x)) 
  
}
gm3(x)
```

## Challenge 2
```{r Challenge 2}
## 2 ways to calculate sum of squares
ss1 <- function(x) {
    sum((x - mean(x))^2)
}
ss1(x)

ss3 <- function(x) {
    sum(x^2) - (sum(x))^2/length(x)
}
ss3(x)

# Calculate Population variance
pop_v <- function(x) {
    sum((x - mean(x))^2)/(length(x))
}
pop_v(x)
``` 

## Challenge 3
```{r Challenge 3}
# Calculate variance of a sample of measurements
sample_v <- function(x) {
    sum((x - mean(x))^2)/(length(x) - 1)
}
sample_v(x)

plot(c(0, 50), c(0, 15), type = "n", xlab = "Sample size", ylab = "Variance")
for (n in seq(5, 50, 5)) # samples of 5, 10, 15... for (n in seq(5, 50,
for (n in seq(5, 50, 5)) # samples of 5, 10, 15... 5)) # samples of 5, 10,
for (n in seq(5, 50, 5)) # samples of 5, 10, 15... 15...
{
    for (i in 1:50) # 50 replicates for (i in 1:50) # 50 replicates
    {
        x <- rnorm(n, mean = 10, sd = 2)
        points(n, var(x))
    }
}
# population standard deviation
pop_sd <- function(x) {
    sqrt(pop_v(x))
}
pop_sd(x)
# sample standard deviation
sample_sd <- function(x) {
    sqrt(sample_v(x))
}
sample_sd(x)
``` 
## Challenge 4
```{r Challenge 4}
# standard error of mean
SE1 <- function(x) {
    sqrt(sample_v(x)/length(x))
}
SE1(x)
# also standard error of mean
SE2 <- function(x) {
    sqrt(var(x)/length(x))
}
SE2(x)
# built in function
library(sciplot)
se(x)
```

## Challenge 5
```{r Challenge 5}
knitr::opts_chunk$set(echo = TRUE)
```